name: Run Tests
run-name: Run Tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          sleep 5
          echo "Finshed tests"
      - name: Failure
        if: github.ref == 'refs/heads/main'
        run: exit 1
